# OUTPUT_LANG_INDEX start from 0
generator-localization-admin:
	node localization/LocalizationGenerator.js OUTPUT_LANG_INDEX=3 SPREADSHEET_ID=1_nKDbwbnqqyRvsvc0cbTvfovAszjDiFjE6v0jBKEUqs GID_ID=mp-admin OUTPUT_FOLDER=../src/i18n/locales/en/defaults.json

